# Generated by Django 4.0.2 on 2022-03-01 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_core', '0002_alter_comments_id_alter_likes_id_alter_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_core.posts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
