# Generated by Django 4.0.2 on 2022-03-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0003_alter_likes_liked_post_alter_likes_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name_plural': 'User likes'},
        ),
    ]
