# Generated by Django 4.0.2 on 2022-03-15 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0005_posts_slug_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='post uuid', unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
