# Generated by Django 4.0.2 on 2022-04-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0010_alter_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
