# Generated by Django 4.0.2 on 2022-04-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0011_posts_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='total_likes',
        ),
    ]
