# Generated by Django 4.0.2 on 2022-05-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_content',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
