# Generated by Django 4.0.2 on 2022-05-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0015_posts_image_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_content',
        ),
    ]
