# Generated by Django 4.0.2 on 2022-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0016_remove_posts_image_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
