# Generated by Django 4.0.2 on 2022-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0017_posts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
